# Gradle Specifications
org.gradle.jvmargs=-Xms256M -Xmx2G
org.gradle.daemon=false

# General Specifications
mc_version=1.12.2
mod_version=1.0.0
forge_version=14.23.5.2855
mod_group=
mod_id=metamechanica
mod_name=Metamechanica
mod_archives_name=Metamechanica
mod_author=Metamechanica
mod_icon=
mod_description=
mod_credits=
