# Gradle Specifications
org.gradle.jvmargs=-Xms256M -Xmx2G
org.gradle.daemon=false

# General Specifications
mc_version=1.12.2
mod_version=0.0.1-ALPHA
forge_version=14.23.5.2855
mod_group=
mod_id=aldynamica
mod_name=Aldynamica
mod_archives_name=Aldynamica
mod_author=kodesque
mod_icon=
mod_description=
mod_credits=
